#!/usr/bin/env bash

echo "| destroy start: Layer1"
# --------------------------------------

echo "1. destroy terraform resources"

terraform destroy -auto-approve

echo "2. stop minikube"

minikube stop

echo "3. delete minikube provider (skipped)"

#minikube delete

# --------------------------------------
echo "| destroy end: Layer1"
