include ../../infrastructure/make/variables.mk
include ../../infrastructure/make/grpc_gen.mk
include ../../infrastructure/make/golang.mk
include ../..//infrastructure/make/skaffold.mk

SERVICE_NAME := product
