#!/usr/bin/env bash

echo "| destroy start: Layer1"
# --------------------------------------

echo "1. destroy terraform resources"

terraform destroy -auto-approve

echo "2. stop colima"

colima stop

echo "3. delete colima provider (skipped)"

#colima delete

# --------------------------------------
echo "| destroy end: Layer1"
